cherry-pick-for
On my systems cut does not work with the unicode '·' character, and complains
that the delimiter must be a single character. Awk has no such problem.
=> cherry-pick-for: use awk instead of cut for utf delimiter

manifest-template.xml.envsubst
also drops repos unused by LTS:
The flatcar-lts-2605 branch still has ebuilds for rkt and docker
(1.12, 17) pointing to the repos under the Kinvolk org but systemd
points to upstream.
=> manifest-template.xml.envsubst: use new repo location instead of forwards

extract-initramfs-from-vmlinuz.sh
This script extracts initramfs rootfs from vmlinuz. It's very specific to flatcar (it does not try to find out other decompression algorithms than zstd, for example).
`binwalk` didn't do the trick for me, since it apparently does not grok zstd, yet. Decompression stuff inspired (or stolen, your pick) from [extract-vmlinux](https://raw.githubusercontent.com/torvalds/linux/master/scripts/extract-vmlinux).
=> Add a script for extracting initramfs from vmlinuz

show-changes
We established the "changelog" folder to prepare the release notes
entries for all new Pull Requests.
Introduce a helper to generate the release note draft based on git
references. The script expects to run in the top level directory for
now and since we do not really use the submodules yet, it still relies
on the repository folders.
```
flatcar-build-scripts/show-changes beta-3066.1.0 alpha-3087.0.0
```
=> show-changes: add script to generate release note draft

create-manifest, mirror-repos-branch, tag-release
For the SDK container we need to make sure that we update the new
coreos-overlay and portage-stable submodules in the scripts repo.
At the same time we need to remain compatible with the old way,
which is still used in LTS.
Leveraging https://github.com/flatcar-linux/scripts/pull/198 we can
use the submodule update helpers and push the update to the release
maintenance branch and also sign the commit as done before. This is
has to be done after the tags for coreos-overlay and portage-stable
are created the old way (which is not covered by the ci-automation).
The other commit is just to move back to the flatcar-linux GitHub org.
None
=> tag-release: update the submodules for the SDK container

mirror-repos-branch, tag-release
The submodule update relies on the submodules being initialized,
make sure we do this when cloning the repo for the first time.
None
=> Release repo setup: clone the repos including submodules

tag-release
LTS still relies on the old way and the submodules does not need to be
updated.
Signed-off-by: Sayan Chowdhury <schowdhury@microsoft.com>
=> tag-release: Ignore updating submodules for LTS

package-diff
- Bc is not available on Flatcar. Use $(()) expressions instead.
- replace unicode characters for reversing
The cut command is a bit inflexible and thus reversing is used.
However, that failed at least on Flatcar when unicode characters are
encountered in SSL cert names.
Replace unicode characters by '?'.
Tested with:
```
CALCSIZE=1 FILE=flatcar_production_image_contents.txt  CHANNEL_A=beta CHANNEL_B=alpha ./package-diff 3066.1.0 3127.0.0
```
=> package-diff: remove dependency on bc

package-diff
Besides the sum of the file sizes the sum of each /usr, /boot, and
/ filesystems's files now gets printed. For the actual disk usage we
need to extend the generation of the metadata files to generate a new
file with the output of something like "df -h /boot/ /usr/ /".
```
$ CALCSIZE=1 FILE=flatcar_production_image_contents.txt  CHANNEL_A=beta CHANNEL_B=alpha ./package-diff 3066.1.0 3127.0.0
diff --git a/tmp/3066.1.0-i6HXHj b/tmp/3127.0.0-dfEKFJ
index 3dc4111..6b9f7a7 100644
--- a/tmp/3066.1.0-i6HXHj
+++ b/tmp/3127.0.0-dfEKFJ
@@ -1,4 +1,4 @@
-Sum: 1158 MiB
-Boot: 46 MiB (must be < 60 MiB or updates will break)
-Usr: 1103 MiB (inc. sparse files/hardlinks)
-Rootfs: 8 MiB
+Sum: 1135 MiB
+Boot: 49 MiB (must be < 60 MiB or updates will break)
+Usr: 1073 MiB (inc. sparse files/hardlinks) …
```
=> package-diff: split up image size report by filesystems

upload_package
* With Nebraska 2.6.0 or newer, GET request returns a json output, which starts all relevant fields under the `.package` field.
We should check if that field exists, to support both 2.6 and pre-2.6.
Split the GET request part into `get_package_id`.
* See also https://github.com/kinvolk/nebraska/blob/dfc08d64bc1a453a4dc411db66139650222b7985/backend/pkg/handler/packages.go#L192 .
* As Nebraska 2.6.0 or newer requires a channels_blacklist (array of strings) to be passed in every POST request, we need to pass an empty array.
* See also https://github.com/kinvolk/nebraska/blob/dfc08d64bc1a453a4dc411db66139650222b7985/backend/api/spec.yaml#L1249
Local test done with Nebraska 2.6.
- Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, …
=> upload_package: fix incompatibilities with Nebraska 2.6

package-discrepancies.sh
From the script:
```
```
This may be a useful tool to see which packages need some accept_keywords changes. Currently limited to production images and developer containers, would be nice to have it also for SDK, but there isn't anything yet.
=> package_discrepancies: New script

tag-release
Since the submodules get out of sync when something new gets checked
out, we can add the argument to update them as well.
Retag a release
None
=> tag-release: do actions on submodules as well

show-changes
The tags may be missing or outdated.
Force a tag update by default which can be disabled with FETCH=0 as env
var. Also give error messages with info which command failed.
With the subdirectores coreos-overlay, portage-stable, scripts:
```
flatcar-build-scripts/show-changes alpha-3139.0.0  alpha-3165.0.0
```
=> show-changes: force tag update by default

cherry-pick-for
The patches GitHub generates don't work well for updating symbolic
links.
Warn against using this script then and make clear that we don't really
need it anymore for change tracking. Also handle submodules to get a
clean state.
Used for cherry-picking a scripts PR
=> cherry-pick-for: warn against using it when symbolic links are changed

tag-release
The update_and_push_version function got changed from a PUSH env var to
a second argument. The tag-release script was not ported and thus
stopped pushing to the release maintenance branch.
Use the new argument instead of the env var.
=> tag-release: port to new update_and_push_version function

cherry-pick-for
The checkout was meant to either check out an existing branch or create
the local branch tracking it from the origin. The --track option
however implied to create the branch always, thus failing when it
exists.
First try to check out the existing branch, then create a local branch
as fallback action.
Works for meᵀᴹ
=> cherry-pick-for: Don't try to create branch but use existing one

create-manifest, tag-release, upload_package
The new LTS will be built from the regular release maintenance branches
and mostly behave like the other channels with regard to how the
releases are built from a major version branch while transitioning
through the channels.
Store the update payloads always in one subdomain from now on instead
of using a different subdomain for LTS.
Will be tested (and fixed if necessary) during the release
=> upload_package: use single update subdomain, Use regular flatcar-VERSION branch for LTS 2022

package-diff
Not all builds are stored in the public bucket but may be available on
Origin or the bincache server.
Add a location parameter to the package-diff tool to fetch the
image/package text files from Origin or bincache.
```
FROM_A=release MODE_B=/developer/ CHANNEL_A=lts CHANNEL_B=developer ./package-diff  2605.27.1  2022.04.28+dev-flatcar-3033-nightly-5522
```
=> package-diff: support different locations

tag-release
When the tag-release script runs again it should use the new tags in
the submodules. However, the regular fetching bailed out since the
old ones would be overwritten.
Force a tag update in the submodules to allow retagging with the
tag-release script.
Retag a release
Retagged a release
=> tag-release: update tags of submodules to allow retagging

update-cloudformation-template
The channels that we need to update are changed here to include LTS
instead of Edge.
=> update-cloudformation-template: Use LTS instead of Edge

is-pr-in-branches, package-diff
Edge is long gone and LTS is now a regular channel.
```
SHOW_PATCHES=0 ~/flatcar-linux/flatcar-build-scripts/is-pr-in-branches https://github.com/ORG/PROJ/pull/NUMBER
```
=> is-pr-in-branches|package-diff: Remove Edge reference and use LTS

show-changes, show-fixed-kernel-cves.py
The release notes have a section for fixed CVEs, filling it needs
manual work when a changelog wasn't added for it the PR that updated
the software component (However, it's also not bad to wait longer with
the CVE changelogs because the information gets more acurate).
Add a helper for generating the markdown output of fixed Linux kernel
CVEs for an update from version A to version B.
- show-changes: Add markdown section headers
The output is used for the markdown document where the sections
should have headers.
```
./show-fixed-kernel-cves.py -f 5.15.37 -t 5.15.43
[CVE-2022-1734](https://nvd.nist.gov/vuln/detail/CVE-2022-1734), [CVE-2022-28893](https://nvd.nist.gov/vuln/detail/CVE-2022-28893), [CVE-2022-1012](https://nvd.nist.gov/vuln/detail/CVE-2022-1012), …
```
=> show-fixed-kernel-cves.py: Helper to find fixed Linux CVEs

devstats
Since the tool doesn't really require SSH access it makes sense to
support cloning via HTTPS. For developers this may be a bit
surprising if a repo's remote can't be used for pushing, therefore,
the behavior has to be set explicitly through an env var.
In an alpine container with
```
apk -U add git grep bash coreutils openssh
./devstats
Cloning flatcar-linux/scripts in /test/../scripts
Cloning failed, try again with NOSSH=1
NOSSH=1 ./devstats
Cloning flatcar-linux/scripts in /test/../scripts
[…]
```
=> devstats: Support cloning without SSH

package-diff
The comparison to a local build is useful when the upload to an
artifact server is not possible or not needed.
Add support for FROM_A|B=file:///some/folder/ as location for the
version folder. It can also be the full path when "." is passed as
version.
```
cd /var/tmp
wget https://alpha.release.flatcar-linux.net/amd64-usr/current/flatcar_production_image_packages.txt
FROM_B=file:///var/tmp/ ./package-diff  3139.2.3 .
```
=> package-diff: support local builds

show-changes
The manual invocation of show-fixed-kernel-cves.py meant that one needs
to find the right kernel versions which is prone to off-by-ones when
reading the update section.
Automate this to save a manual step and prevent mistakes.
```
flatcar-build-scripts/show-changes stable-3139.2.2 stable-3139.2.3
```
=> show-changes: Autogenerate fixed kernel CVE entries

show-changes
The ls-tree --object-only parameter is not supported in git 2.32 which
is the git version in Flatcar Stable and in use on our build servers.
Filter the output with awk to find the commit ID.
Needed for https://github.com/flatcar-linux/scripts/pull/375
I did the following to check it works on Flatcar Stable with a python3 command in PATH
```
FETCH=0 flatcar-build-scripts/show-changes stable-3139.2.2 stable-3139.2.3
```
=> show-changes: support git 2.32

show-changes
A newly created git reference may not be present in the local
repository which fails the submodule reference detection.
Fetch the repository before using any new references.
=> show-changes: Fetch scripts repo tags before using the first ref

show-changes
Since the output is not formatted correctly, 
we need to manually update the hackmd sheet.
=> show-changes: Align the format of output with the existing

devstats, mirror-repos-branch, tag-release
The "flatcar-linux" org will be renamed to "flatcar". For renames, there are no redirections in place and we have to update all links.
Merge when org rename is done.
(The old pipeline manifest creation is left as is, we can delete it in the future but let's keep it around until the first release with the new pipeline is done)
=> Prepare github org rename

devstats
This fixes the flatcar-linux -> flatcar rename that was also done for the repo name by mistake in c3bbc10d.
```
./devstats 2020-01-01
SKIP_FETCH=1 ./devstats 2020-01-01
```
=> devstats: Fix FLUO repo name

sync-with-gentoo
Add amend mode that updates the commit message to use the new used hash sum of the commit. (by @krnowak )
Detect `metadata/glsa` to sync only the metadata/glsa directory. It is needed for a montly Github Actions for syncing GLSA metadata.
=> sync-gentoo-glsa: add amend mode, detect metadata/glsa

devstats
Show the sum of all commit counts as summary.
`SKIP_FETCH=1 DEBUG=1 ./devstats` and `SKIP_FETCH=1 ./devstats 2022-01-01`
=> devstats: Show commit count as summary

package-diff, size-change-report.sh
I wrote a script to analyze why the image size for arm64 would grow by 70mb for one of the weekly updates. I think it can be useful in the image changes job.
This PR also tries to discard hardlinks in the size calculations in package-diff. This results in numbers lower by 500mb.
=> Add file size change reporting script (also fix hardlink accounting in package-diff)

size-change-report.sh
Looks like bash in CI complains about the xgit-diff function having an invalid identifier. Rename it to xgit and pass the diff word as a parameter.
=> size-change-report: Rename the git function

size-change-report.sh
The `sort | head` pipeline results in sort complaining about a broken stdout pipe. This kinda makes sense, because sort wants to write all the sorted results, while head just reads first 10 lines and closes its input end of the pipe. For some reason I can't reproduce it locally, but it's annoying to see those messages in the image differences job. Since we already ignore errors from sort, send its complaints to /dev/null too.
=> size-change-report: Silence the sort

devstats
The GitHub username is sometimes directly used if an action is done through the web UI or similar, depending on the settings. For these cases we can link the commits to the existing entries to prevent duplicates.
=> devstats: Add one more entry to match GitHub usernames

upload_package
- upload_package: Report failed registrations as failures
The script doesn't run with pipefail, thus the POST failing was ignored 
as long as jq did not give an error code.                               
Split the line into two to make sure we catch errors without requiring  
set -o pipefail. 
- upload_package: Allow to skip the upload to Origin
For testing we don't want to upload the file because we might not even
have a vaild file to test.
Allow to skip the upload, making it possible to run as:
touch /tmp/flatcar_production_update.gz
NOUPLOAD=1 ./upload_package /tmp https://staging.updateservice.flatcar-linux.net notused 9.9.9
Tested on staging
=> upload_package: Report failed registrations as failures

mirror-repos-branch, show-changes, tag-release
The change prepared in https://github.com/flatcar/scripts/pull/699 means that we don't use the coreos-overlay/portage-stable repos anymore.
Skip these repositories and the submodule handling, too. Leave existing logic there to support doing releases the old way (at least for the nearer future).
Merge before trying to do a release. Also required for proper output in the image-changes job.
Local test diff for `tag-release` was
```
diff --git a/tag-release b/tag-release
index aca1bcf..e105c98 100755
--- a/tag-release
+++ b/tag-release
@@ -26,6 +26,9 @@ if [ "$CHANNEL" = lts ] && [ "$MAJOR" = "2605" ]; then
MAINT="flatcar-lts"
fi
+MAINT="kai/t"
+MAJOR="lo/merge-submodules-to-paths"
+
SCRIPTS_REF="${SCRIPTS_REF-origin/$MAINT-$MAJOR}"
OVERLAY_REF="${OVERLAY_REF-origin/$MAINT-$MAJOR}" …
```
=> Adjust release scripts to work with scripts as monorepo

sync-with-gentoo
It does not need to be a top-level directory directory of a git repository, but rather a top-level directory of an ebuild repository.
Needed to port weekly package updates to merged scripts repo (https://github.com/flatcar/scripts/pull/699)
=> swg: Relax the working directory requirements

show-fixed-kernel-cves.py
In some cases, when running `show-fixed-kernel-cves.py` with python 3.7+, it fails to run with the following errors:
```
Traceback (most recent call last):
File ".../show-fixed-kernel-cves.py", line 68, in <module>
print_fixed_linux_cves(options.from_version, options.to_version)
File ".../show-fixed-kernel-cves.py",
line 55, in print_fixed_linux_cves
for cve, _ in sorted(cvelist):
TypeError: '<' not supported between instances of 'dict' and 'dict'
```
To solve that, ignore values from the list.
=> show-fixed-kernel-cves: fix type error when converting cve list

download_payloads, generate_payload
- download_payloads: Add helper script for update payload fetching
The update payload fetching was a simple wget invocation until now but
with OEM payloads and other future Flatcar extensions this gets more
complicated.
Add a script that finds out which extension payloads are available based
on the Caddy JSON output.
- generate_payload: Create extension update payloads
When a release has extension update payloads for OEM software these
should be signed as well.
Extend the generate_payload script to detect additional extension files
and generate signed payloads for them.
```
cd /run/media/usb/sdk/src/scripts/data/
~/flatcar/flatcar-build-scripts/download_payloads alpha:1786.0.0 beta:1781.2.0
```
The above and
```
PROTOPATH=src/update_engine/ ./decode_payload …
```
=> generate_payload: Create extension update payloads

generate_payload, upload_package
Nebraska should now deliver OEM update payloads through the extra_files mechanism (besides OEM extensions other Flatcar extensions will be added in the future, too).
Upload the additional payloads to Origin and register them in the extra_files section when creating a package.
These new scripts must be used to publish the next releases.
```
NOUPLOAD=1 ./upload_package /run/media/usb/sdk/src/scripts/data/test/3717.0.0/ https://staging.updateservice.flatcar-linux.net some.release.flatcar-linux.net 9999.9.9
```
=> upload_package: Register extension payloads in update package

package-diff, show-changes, size-change-report.sh
Please see each of the commit for the changes made and some reasoning.
=> Changes and fixes for showing reports against nightly releases and OEM sysexts

upload_package
The base directory is part of the filename entry in the sha256sums file when it's an absolute path.
Don't leak any absolute paths into the checksum file.
Use for next release upload
None, todo in next release
=> upload_package: Don't leak directory name into sha256sums file

show-changes
Single quotes inside a line like below are treated as a part of the value:
: "${foo:='bar'}"
If foo is empty or unset then it will be set to "'bar'", instead of just "bar". This resulted in the script complaining that git can't operate on directory "'scripts'".
=> show-changes: Fix excessive quoting

tag-release
The tagging function was changed in the scripts repo with https://github.com/flatcar/scripts/pull/799 (not on all branches but this is solved now) and since the tag-release script uses it we also have to adjust the function call here.
Retag Alpha
None
=> tag-release: Port to new tagging function

spawn-az-vm
Sometimes the CI does not give enough flexiblity to iterate over fixes. Using one's own laptop is also not always desirable.
Add a small helper script to spawn an Azure VM with "az" that can build one or more branches, also after creation. Usage is as follows:
`./spawn-az-vm --name N --ssh-key FILE --resource-group RG --location LOC --create-vm --ignition IGN BRANCHES...`
The Ignition file is optional but useful to disable updates or change the SSH port.
=> spawn-az-vm: Add development helper to build a branch on a temporary VM

spawn-az-vm
The westus location is better to use because it's closer to our Origin server that hosts the source archive. It turns out that using more cores also brings a speed up because more emerge tasks get started.
build_packages: Elapsed time (build_packages): 58m52s
Total time to qemu image: 1h13m
=> spawn-az-vm: Update defaults

resty, upload_package
As Mathieu found out, his new curl version won't process the empty string being passed to curl as argument, resulting from the no-body case for GET. The empty string was treated as additional URL which was skipped over in the past with a warning but now it's a hard error.
With
```
touch /tmp/flatcar_production_update.gz
NOUPLOAD=1 ./upload_package /tmp https://staging.updateservice.flatcar-linux.net notused 9.9.9
```
I checked that the `get_package_id` shows the error for wrong curl arguments when switching the `body_arg=()` assignment to `=(--unknown)`. It now also prints the curl errors when curl hits an HTTP error code which is the case for the final POST in the above test.
=> resty: Add workaround for new curl versions

sync-with-gentoo
We want to call our own repo portage-stable (or soon gentoo-subset) so stop setting this file back to "gentoo". It wasn't an issue before because we set the name to portage-stable in layout.conf, but you're not supposed to set it there anymore.
The change achieves this with rsync, which also gives the benefit of less disk churn.
I did consider doing this exclusion via portage-stable-packages-list, but one line is passed to sync-with-gentoo at a time, which doesn't really allow for exclusions. sync-with-gentoo already has specific rules for certain directories, so this doesn't seem so bad.
Try it as usual and see whether repo_name changes.
I have manually run sync-with-gentoo locally to see the effect on repo_name and other files.
=> Exclude profiles/repo_name when syncing with Gentoo

size-change-report.sh
It's for printing file size changes for podman, python and zfs sysext that we generate.
=> size-change-report: Add support for extra sysext report files

sync-with-gentoo
Weekly updates github action in scripts is still using this script, so let's update it to include the DCO in the commits.
=> sync-with-gentoo: Add signoff to commits

spawn-az-vm
The image build didn't include the sysext images and we can also use v6 VMs now on Azure.
=> spawn-az-vm: Update settings

spawn-az-vm
- spawn-az-vm: Add build time optimizations
To have faster build times we can build in a tmpfs and use emerge
options for parallel package installation.
Write the emerge options out before the build starts. Due to the nested
shells, base64 was the easiest approach. Also set up /tmp as place for
Docker storage from Ignition (optional).
- spawn-az-vm: Remove outdated usage of open ports    
This didn't work anyway because nowadays a VPN is used instead.
=> spawn-az-vm: Add build time optimizations
